// =============================================================================
// Shared types for the elements module system.
//
// Every renderable element (building / facility / plant / person) registers
// one or more variants. A variant is a tuple of (id, footprint, features).
// - id        — string slug like 'classic' | 'modern' | 'neon'.
// - footprint — axis-aligned half-extents used by verifyLayout to detect
//               road occupation and pairwise overlaps. Optional sweepR
//               captures rotating parts (wind blades) that extend beyond OBB.
// - features  — element-specific payload (palette, optional roof unit, etc.).
//
// Phase 1 invariant: every element registers ONE variant with id 'classic'
// matching the current visual. Phase 2 adds 'modern' / 'neon' / etc.
// =============================================================================

export interface Footprint {
  halfW: number
  halfD: number
  sweepR?: number
}

export interface ElementVariant<F = unknown> {
  id: string
  footprint: Footprint
  features?: F
}

// -----------------------------------------------------------------------------
// Building-specific types (procedural — instances generated by genBuildings).
// -----------------------------------------------------------------------------

export type BuildingType =
  | 'office'
  | 'warehouse'
  | 'factory'
  | 'apartment'
  | 'house'
  | 'skyscraper'
  | 'townhouse'
  | 'energy-lab'
  | 'microgrid-control'
  | 'parking-deck'
  | 'service-depot'
  | 'utility-shed'
  | 'green-apartment'

export type BuildingVariant = 'classic' | 'modern' | 'industrial' | 'green' | 'compact'

export type BuildingUseCategory =
  | 'residential'
  | 'office-commercial'
  | 'community-support'
  | 'energy'
  | 'industrial-logistics'

export type BuildingHeightBand = 'low-rise' | 'mid-rise' | 'high-rise'

export type BuildingShapeCategory =
  | 'residential-low'
  | 'residential-mid'
  | 'residential-high'
  | 'office-commercial'
  | 'support-facility'
  | 'energy'
  | 'industrial-logistics'

export type SupportFacilityKind =
  | 'guard-booth'
  | 'garage-entry'
  | 'community-center'
  | 'energy-service-station'
  | 'management-kiosk'

export interface BuildingDef {
  pos: [number, number]
  w: number
  d: number
  h: number
  rot: number
  topHex: string
  type: BuildingType
  variant: BuildingVariant
  hasRoofUnit: boolean
  hasPV: boolean
  hasRailing: boolean
  roofHex: string
  useCategory?: BuildingUseCategory
  heightBand?: BuildingHeightBand
  shapeCategory?: BuildingShapeCategory
  shapeFamily?: string
  shapeId?: string
  labelZh?: string
  requiredSilhouetteFeatures?: string[]
  supportKind?: SupportFacilityKind
  visualFootprint?: Footprint
  /** Marks a building generated by the suburban falloff belt
   *  (cityGenerator.buildOutskirtsBelt). Rendered by the cheap instanced
   *  <OutskirtsBuildings> path instead of the full per-type component tree, so
   *  the mid/far-distance suburb doesn't blow the draw-call budget. */
  outskirts?: boolean
}

export type District = 'cbd' | 'midrise' | 'residential' | 'outer-residential' | 'industrial' | 'commercial'

export interface CityBlock {
  bounds: [number, number, number, number] // [x0, z0, x1, z1]
  district: District
}
