import { useMemo } from 'react'
import { Instance, Instances } from '@react-three/drei'
import type { BuildingDef } from '../types'
import { buildCity } from '../../scene/cityGenerator'

// =============================================================================
// OutskirtsBuildings — instanced renderer for the suburban falloff belt.
//
// The belt is generated by cityGenerator.buildOutskirtsBelt() and tagged
// `outskirts: true`. It sits at mid/far distance (r 24→38), so per-building
// detail (railings, rooftop PV, dormers) is wasted — and routing ~150 belt
// buildings through the full per-type component tree would add hundreds of
// draw calls and blow the showroom draw-call budget.
//
// Instead we draw the whole belt with TWO InstancedMesh batches (body + roof
// cap), reusing the generator's topHex / roofHex so the palette stays coherent
// with the core city. ~2 draw calls regardless of building count.
// =============================================================================

export function OutskirtsBuildings() {
  const belt = useMemo<BuildingDef[]>(
    () => buildCity().filter((b) => b.outskirts),
    [],
  )

  if (belt.length === 0) return null

  return (
    <group>
      {/* Bodies */}
      <Instances limit={belt.length} castShadow receiveShadow>
        <boxGeometry args={[1, 1, 1]} />
        <meshLambertMaterial />
        {belt.map((b, i) => (
          <Instance
            key={i}
            position={[b.pos[0], b.h / 2, b.pos[1]]}
            rotation={[0, b.rot, 0]}
            scale={[b.w, b.h, b.d]}
            color={b.topHex}
          />
        ))}
      </Instances>

      {/* Roof caps — a thin slab slightly oversized so the silhouette reads as
          a pitched/parapet roof, not a bare box top. */}
      <Instances limit={belt.length} castShadow>
        <boxGeometry args={[1, 1, 1]} />
        <meshLambertMaterial />
        {belt.map((b, i) => (
          <Instance
            key={i}
            position={[b.pos[0], b.h + 0.06, b.pos[1]]}
            rotation={[0, b.rot, 0]}
            scale={[b.w * 1.06, 0.12, b.d * 1.06]}
            color={b.roofHex}
          />
        ))}
      </Instances>
    </group>
  )
}
